baseurl: http://www.codingbaby.com
permalink: /blog/:year/:month/:day/:title
markdown: rdiscount
highlighter:       rouge
pygments: true
date_format: "ordinal"
paginate: 15
paginate_path: "blog/page:num"
