url: "http://vsmysee.github.io"
baseurl: ""
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
date_format: "ordinal"
paginate: 100
paginate_path: "blog/page:num"
gems: [jekyll-paginate]
